---
# yaml-language-server: $schema=https://crd.movishell.pl/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-16
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
#  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart
  mode: standalone
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: nfs-csi
    size: 20Gi
  postgresql:
    shared_preload_libraries: ["vectors.so"]
    parameters:
      max_connections: "300"
      work_mem: 64MB
      shared_buffers: 128MB
#  superuserSecret:
#    name: cloudnative-pg-secret
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      memory: 2Gi