# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:T6BUJjtJkaTqtfp/yjXzzAofvF585pJ058DwSwTN6Yf1kd2NwzGxA7Bx0iVN8CUmbutUGFYNUyGLIgPNgZV1Q30sZSlHSHpn0Oe3cDo1kL/SBDbMRq1jwcxcUq4BGlm5Gy59p2TqXVQykpFmOlALRiWE5FSFq07CYoF8+bFiBfSsBcMjLm4ciezE0r6WcHmBrBzawRMWyuc+dNgKQJQStibEs1mrWk5nrWqt1340jtJfc32JAQ==,iv:rQ/xkDiRsO8+DsD1Jy894v2vVaX27IEvBBKDBLQGpR4=,tag:5N4lClTUc+Ea6rMVvdZdtQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OW9Xd2JWOFdBWk9YNUJp
        VW1SNmprajRhR0Z1NWtNenpiK0h6SDFnMzFjCkxSQ3B0NVpRRng5WFBXOHJGZE1N
        My9UMVlvcmlGTUJTT2VIbjlTb0lmWTAKLS0tIHZjZHNyMm9XMGdnRDk2OVl3V1pk
        YWRkU2p0ZGZqNStvNkdPcmNhU1phZ2sKrXSF6mGlJWrhPr0Qg2m9aYdxxTZv7OsM
        fklrn5STrFaZ9uGbv567Ep6xASRXZ5BTNf2wm2UPERSaAZrbmcPsog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T14:20:13Z"
  mac: ENC[AES256_GCM,data:8O4N827Lp95GdxFNqlOAbmiEIMrknxy6OwxynjQbPm3dgarOzrTnhuzVyWQuRBHRygaxlFtHxtiNLhxCRe2IkEvAEzvuei0goUsaJslkswAENW1UUJPJ36eNs3dcM9IYfslO+HH2kDA77HERAl07M+zg9k/Qox5T/pY7k0twtVc=,iv:iosOzvJzsbOM0tu8k17MxPNaduezYVQCUalLRLvENdc=,tag:xIahZQZdeTz40Hgy7UlsHg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
