# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:qJMIvZhLMiNZp46kxP95O2dFwwqgScmv9nAeCE2zPI7nheB2804CeMoQOQGdF6R6m0a5qiQs8oaaWHLSZVJYqVglbcyVj9GLof+CrqE2eBhtLUIT+QDHqwrGGMVTqufgXfklLyTZhiedyt1dZ8HoFUWMajc51QUTIRu7DdNG+zKx/8OOjhQVtWq3wqUQ4+H+QEZ8GtlWljR+vJzrUxgtfSikngoSZX7As09GxgGFUA==,iv:wneOtXeyWmxC4RYVbPLxhiYpdxjKEeII+XVYmzwWMGA=,tag:wYUen/hN4DhS3zC5KHGhhw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1earun57070y7d55fv7ev4sc88uk65tuxyng8tyan77hsp8n57v0sq3jxkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUlBGbVcyYlVqdVhoOFUv
        MnNYQjN2TVBTc2V1Tmgzb2srS09xTklwcUI4CnNnTkZXUFJXOWZBN3B2VWVvYnRC
        UGJIZXAvSEsvUXlSamUvSm9KYjNSQU0KLS0tIHJtWnpiL2JaVkxFWDVGNUU5QVZ3
        ZG04ZzcrTCtXU1o2TTlIOGZnUzZDbE0KReuJ04+AZHIQFMr3eMByB0pnLT23DD6T
        4OZSwUnLp7/hymr/QT+y8lk3c7ZXOKafbYTSzNLimxPw+gh5fZ/K3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T10:59:47Z"
  mac: ENC[AES256_GCM,data:XaYKRpTFpxHak1dIDS/Ip+qdgOGCKQJYDuCSkkmaoE4HpOsbnC3NqN+Rzi/ifomBmwSBUhuznQxe+gUV1vy98I/IQcv0QPQYEn2n51YF1kR2HOy2FdszLUBfzJPxoqUImH4sfMxeIsMoqiZR9Fxa2vhvwlqrSMP0Ua1Qz7c+rUg=,iv:7ExEJdFGRAlp4dUAiSNvq8b+QmCuSyuENDgJA6iDL1Q=,tag:QCjgxNt7xjWo+nxFZJwJnw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
