# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:NNQo6XboDIVNLP06pGOPkH8mUn1u8bXX2r4EwmTdQup7qQ0O3FHCw/mTkl7fcsF57aVjBw8//6MoxKXvEIe7StSCQ3BE3PRLPQIojfeq4ivrO5lPoEfuvhSaAosdcQGSTNqI8eNQTu5uBILfGC0sm9Zrb7MDR0kk3UBP4OJnSCT1WMeX2FwW3fSTfpHlWsTotBCUYa1XJ0QjHNhGBRHHOEvCJ2f650kjtrjOz2o3Nz6xv4gjVQ==,iv:+s5Q+izREEqETvyS8wzjaJzhr76nPlJSbgz/dR1RWss=,tag:UzKO0FxCdFXntpGULmBycQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRDFCYjRoTURSMExoRitl
        eVVUdXVyTytPczZhaE43UlVhUFppdysvbW5NCjZBeC93aWxlU1pmbTNMaENsSndO
        OHR5ZGFldSt1cXYvK1Z4QkdYM3I1ZHcKLS0tIEtweU5XZnhWVHdJOERodngzWG1z
        cWxkNmUweDN0d21MQ2JEUm1EQm5jOXcKdXhF6qipuEU7fnFielUbVdvv8h+uUjih
        UUnlYREJb9yqnJYuzEy3cenAygj9MN5y26ZvDoQHBoYxSUCYJmYi8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T09:45:41Z"
  mac: ENC[AES256_GCM,data:WQUQPbiNsjweVz30D/sBn9uK4ayO8toJx24dxsNovGRh/toPCYIhkJE247vVtN4GD2Kam0tkREFVP4sRFfPaIaYQcYA9M3aepsX8VGIZMZGt5Y0i48FluDDQR8yyyaZkWQuvzJKiu28+EoyJEk8I3H88Mizr0iNb/4xb/6+/r6k=,iv:0f7X/Fy4SOQswtARFg3oCFwcsR8ligLVjEGCjqYuzbM=,tag:cJe8zmkileae5LN+TyTT0A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
