- Infrastructure:
    - Proxmox VE:
        icon: proxmox
        href: https://proxmox.${SECRET_DOMAIN}
        description: Proxmox Virtual Environment
        widget:
          type: proxmox
          url: https://proxmox.${SECRET_DOMAIN}:8006
          username: {{ PROXMOX_API_TOKEN_ID }}
          password: {{ PROXMOX_API_TOKEN_SECRET }}
- Observability:
    - Cloudflared:
        href: https://dash.cloudflare.com/
        icon: cloudflare-zero-trust
        description: Cloudflared Tunnel Status
        widget:
          type: cloudflared
          accountid: {{ CF_ACCOUNT_ID }}
          tunnelid: {{ CF_TUNNEL_ID }}
          key: {{ CF_API_TOKEN }}
- Calendar:
    - Agenda:
        widget:
          type: calendar
          view: agenda
          maxEvents: 20
          integrations:
            - type: sonarr
              service_group: Downloads
              service_name: Sonarr
            - type: radarr
              service_group: Downloads
              service_name: Radarr
            - type: readarr
              service_group: Downloads
              service_name: Readarr
