- resources:
    backend: kubernetes
    cpu: true
    expanded: true
    memory: true
- kubernetes:
    cluster:
      cpu: true
      label: cluster
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: false
      showLabel: true
- search:
    provider: [duckduckgo, google]
    target: _blank
- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
