# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:KOB/WPtxOaaGaPnz/qGLVcCki34xjrUbPMnL4P+V5yKQ+Rxjy8K/AA==,iv:fSRnd1D2w7+K6HmvaqnVsfRFxtrRCQUp7x2V6oijxb4=,tag:8eT5/d2PprJ9iQFNnFtaZA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V2tYTnczaktJai9pVG9o
        b2FxWkxsd24ycEFQK01rWUdaMTZtS1c3UERNCitueGdZTzhqVVdwSVcwemJRTG1K
        cUlGSldndzJNQlYvVEp4WE9rdmNYWFkKLS0tIEFET3ZIZkNsY2pJWFJud1V0REVS
        RjczWDNVUGxzdTg0ejYxSldnUWgxY0UKw2vOFUOdA8/lX9Gx9PV6rnaM5jhh0LJl
        HJjwkJ73wDx2xYANKnK2MLgzTAxrqUqq5lO9XRKN6g+xgUnZYoeQzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-27T20:18:31Z"
  mac: ENC[AES256_GCM,data:fdiX61n+QQrKiVXfAEzSVadSxyAK+uLHhaCAHgx5yjPwndTKJbFv5J5FUcY8PFJkX3b6uczCyonpjgOdbos5UoVDLI5JIIMp7QfKzBVPiRMN5EfcqDLsuVQWppkyxh/kdI2oQAcnWqjRi1XoFFONCZyUaGZ4qoKCP5VibrcrJNU=,iv:XoBzCPeQiBZOynLgfLUOuokY03lA8HATKY03rh0xLuc=,tag:hdvNtpxkLoWTvnwUNgf5yQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
