# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+WT5aDIitI5Fs001O1PL6kGhBv/zadTFRHi8KAmTeWsH/oY5KayVrg==,iv:yK5m1DBKxSo8yCUkAIKq1xIT+a78HmZZ8DHuH3tR81k=,tag:GFvPMTLNayD24Nly/hc+9w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeUttVlNiNUdVMGNaWWFk
        UWJrLzVmQlNTNWpTbjJPRGFPeC94ZGtFMHk4CnhtNU9NWUx3QkI4OUxQZTA3ZFR4
        SVE1a1J3dktZRXpHamtzT0lzYVJtZTQKLS0tIDNFMElqczhESlZaczNId050cjIx
        ekpGMW80T3JjZ0R4VSt0aHl1aUVGTXcKx/CFGBbjQHrDOlB1AoWgBCuuObwxNFTW
        nz1vGUjA1iQebK08PskcZJyTwr36mHFEAcKNNIXztIzQZ90qSW3gHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T14:20:13Z"
  mac: ENC[AES256_GCM,data:ifUeV7a/6SAMhC7HXDhjmQHwmS4TwV4IT6z6mF2BQ7MsuHh5qW45drrDJhpn73+dt6uPgoG0HMk87bTOwr8tAnmxaZiSBVrlr++DpLBvULwbmxawB71VRWxaFIarzdvLmv8awnzm3nvCZ23UCQULs7uBqMmJukwCWo1kD03wSYs=,iv:p3YBZThgxRGVGtac7jO3dAmcWvwEW8P8bxxxu2utV0U=,tag:IQipuURpH15m7p0woapdCw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
