# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:z6pfpXSL4giafqMX0CcptUZPEDrRI1ezcUiZjSF7LS65s/+bcelBUw==,iv:ywdavV7/wA1AlGetgyXVt3/I+NuePrEqpiG66Ku8Co4=,tag:UP2JL51Sbkn98YKyE/kn3g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1earun57070y7d55fv7ev4sc88uk65tuxyng8tyan77hsp8n57v0sq3jxkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdk52ZFNmWGYyNlBwOFFB
        T3d4NHluQ20vMlZ5dkMvaXRWSXMxWGc5RkFZCmNsWU1QcWlVMmhXVmpkTGxETmt0
        ekMrTm54ZVBvN2xIMDVGWHRkbkdwM0UKLS0tIGNYYk4wTkJnZFBGSGRWWHpaQ1Zi
        dDBpUGtodkF2OEk0RDdTRGt3QVI1ME0KXmB0W48hHntWY4JeGj4rXgnq+KG5P6d7
        /eLy1X+tGgdaJJLy8zNMUiKcz3JXWxyuoqo7t6+JXEwXrVFA3hy0IQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T10:49:59Z"
  mac: ENC[AES256_GCM,data:U+Hvev5gum3cVno9nNygLhYd8fQeX0y/YuXbh7kGbi5dDvLeX+lAjES/BeV7CRSsiw5xFFInu67ikzSQoBdfWEebwLMhS1AMCmfV0xCfhmVVFIDFOsOI6mGOmals5UTWmD1qQ9s8szbul5a8InLSbtSLq4wTxc1JoaJlRTeruQ8=,iv:ATeGVo3aRoPMgou7jdbNIBnDqO2eINBC9A9wSI0jAyk=,tag:wliSZHkwkZ1XbccgAzZHfg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
