apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-user: ENC[AES256_GCM,data:OOPnuk4=,iv:GW47Iw+foYRKwGtuiTnpwYMZA21IHJqXD818CHfzgds=,tag:p5sDKmDY6qojVGNKodSNZA==,type:str]
  admin-password: ENC[AES256_GCM,data:S9Kn7UzYf1Mr,iv:+q906SiqiWbHiho9uTB2ID8sz4OOKha26BHSMj4/KX4=,tag:UM4/qKEEGNeENEHQP/diPA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1earun57070y7d55fv7ev4sc88uk65tuxyng8tyan77hsp8n57v0sq3jxkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ais5ZGN2eTVVLzU2aEpK
        cytEdm1qTy9XQWxBdlhsVXZob0J3U1d1bXp3CkR6bFh5SlJHbHJVMVUzYUtRaUND
        VTgrKzhwQXpnOHdoK2x1VU5mTTRNSGcKLS0tIG43SmdCREY0Si9pTndEYnNDaXZw
        a3Q2dDQxSWhVWnZzY2MyTFJhZWhRajgKUv6vgYkCaZUe71NE+FaJybZB2hw4Enpq
        hNfXrxISC+V9ZmNlBa+o/5giylexrqdPl1/NrdJfBDjfRwJ4n7NFjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T09:14:31Z"
  mac: ENC[AES256_GCM,data:0TKNCZ1TfHUlJSv+Y+H/IKmaw3zr5YAOfiHPdGHRba7USWhhVEvpbkJKUISM74PbMGfRpHUSnr53Q2LVYzv+cSF9VfwFvWYBtcYaqoDgovJ0wODaiJ3s0XR5WK9RuoGFeNtkfNZ0wRxUHWMcxHyl34d0crhIeaGFTbL5VyPwv6s=,iv:9m567SboPBxnVhj77F+uLHWdnj6RiUSIUG9WJWuC1Ko=,tag:DT3n+8t4ld6fGC9ES+rzCw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4