apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-user: ENC[AES256_GCM,data:d2JHY24=,iv:AB7uy2Mdziy5M48lNeDPniNgkTrQU4JArZVm7yKxkmE=,tag:o97dAtuic9jkQ9KJsQgYAw==,type:str]
  admin-password: ENC[AES256_GCM,data:VsjOt/lDlsod,iv:p82lX4/b4iXt1JqexBUfmVM9P3i8vwWOh3mgni+JkA0=,tag:TaxX0YIgz0ZvzLSaZaH7kA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSHh0N1JnRHZUSmV5MDBz
        K25reGVpUGRMRkwvVElmZGwrUUdiWk41dUdFCnZmZ1lITk5sczNMTVJjMlhuYnlB
        dW85bk5kd2tmdXNxZFpnV1lvdjZEVEkKLS0tIGVSWXZZNkd5ZXIzdjhxV0tHSWlm
        VmhHZHhYK1Bmd0NNQ0l0ZW9WS3M2T0EKHThlxvFFV+P5tW6fO5m/DQfOZWuv6OWx
        6aQtDFxzzfNce+hzw2rYZ3piNael75XNVoXl0M+Sr5zcQRekQCGkgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T13:01:27Z"
  mac: ENC[AES256_GCM,data:s/ikYcn/C8+4aYKBplBjdXW1ZmLPPnG1S6A0riwxUHI4xMMCXFq0eL+JPorxnrJA2zONWvZPC+oGirzHWHPbJITQKD7VwbCcVMSa3/jYKTGywnwES9nXqUgO1w1iaLuj+QjCIgMm0K+x3e/NESBes9q/Y335KvqxwqGjgwADI2Q=,iv:lveqHlR2p9XII0CDPAbz3jurRq5AwzU4necchZGYwV0=,tag:iJ1YxHHSKKFGkVcTtMpCHw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
