apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
stringData:
  apikey: ENC[AES256_GCM,data:VCPtV9n139+XOkLQfFwQ2SVh/i/Brjd3vqZamZ25ORE=,iv:nKFPGMjzEZcr9PV3JAr8nojggop1C+anMaMAhYrvfAw=,tag:BRsn1zdozRxQY9mD7NyEVw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR1loQzg1V0RWTFZuYk4x
        V2VueWtXNFppRHZGb2pRclpGeDFzV3RyRjE4Cnd0bjVWT2VMeVJUdmxqa21RMmlL
        SUtlS085YUI5bW0za2RSRWZ5MTRCelUKLS0tIFBoVkczVWNXVDQ3QjJ5YTNwZG1U
        VmNDbGk0cW5vUEVKNlU5cGdkUEZVMjAK0Pov6z7kIBV/1n9mmfONCqkHDQTYmbae
        EMa5Xvhfu5Bet8LFVCMXgvce4EB3FnCND97h0g54VQ+vlSntz7Y9gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T13:02:33Z"
  mac: ENC[AES256_GCM,data:LSqImCh5a7qj+iVlhZuwUzW4S5oX5lYKbzVfoENHBYZD1DX9IWCfTZ6o/jnJueaKVRoIT2zqttBSoNwRaRHEUGpcdEDtBlrLzSaDHIt8TPjc/jBXiZS88iCnPxSS2NZ+BogKBYAF+zCr1ieL2dbxnytXQykbZlrnGdxDc2u7a18=,iv:V3yZoK1MNjggADu0nmQf23Qj7rxvIlbXlaS0ghd3Z50=,tag:kkQZm6iwMR8vXVPR5GSMFQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
