# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  namespace: database
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:yMpMBZOs+emIoA==,iv:Tb0gWuebuzuEg0afsTlcSWErfcQ/3/ImR7ayNi6UJ/s=,tag:gBWrG7YyFHUG7hMzXlotRg==,type:str]
  password: ENC[AES256_GCM,data:ht2ziT1ulVgG9bfFefwMlw==,iv:PksE+rXzqbjLfrYY4FHZ/3WGk/9eZsbfTtNCJsL3nhY=,tag:WFu+oSgCI7gSPnlPQe04/g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadU91UjQ5UlJKVXQ2dEpJ
        T3Q1d1V6VWxocGlzOEFlNEg2L25lSFNBcHh3CnkrRlFKSVNvTGR1alUvQUFneWlt
        VXF4RVVmSUd6VlE4Ly8rcGdJZXY2WDQKLS0tIE02Z2ZYb1pkazA5M3AyY1E5ditt
        bHVZZEpuSWk3S3JaQk90L01oeHQxSk0KvNxbknT2TTyz/Q7T8t+yc6RoT9YP38F8
        WrGCMtGQpeOB0GtW4nJFwMbBNUCTaCd9bTLC2ipaXv0elskBlardEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-25T20:44:17Z"
  mac: ENC[AES256_GCM,data:Hcu8vtPQvdRnCeCmQ9t0/SpOSgvuB/r+UaeWQkP1SQU2tFqGFX2Uhs54wKIvYTvj7cmVDZMVn2TlwB0ggpYZWran2dz7qAB7HEGmgBFQeThVldR6Te1JAAq6JT03Qs/uako3koA8EVUx4xtmSntsryYcZXv9mDLPqum/ofZwuN4=,iv:rFZ5q/mTRoP2pX0HSzGR0bP+ulLwdXyo95ZO5uTEXV0=,tag:cQ+qR3q/o0vITJuljZbtwA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
