apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:IUeiyig=,iv:dX4nDyKN3KNfMudTMWWm6aHNdNmYNDg1vi6+sBiS92U=,tag:/0CjP1Qd3q99y4KTFkPdEg==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:EZOMOeOrsMzQ,iv:iZz+eIH8uEuJ/RueKCafjA6ZtK/qcxBnUYLCOBHTZzw=,tag:sOZJ+dV0wTj1WpBJ2au5aw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1earun57070y7d55fv7ev4sc88uk65tuxyng8tyan77hsp8n57v0sq3jxkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S3NmUmNhOFA3MFMwU3lu
        dUdSaVkrdytCRCtlTGo3S3FQSlRHbTBxRXdzCmZFSVNEcDR4MDlicXFRNFd3ZlNh
        bDQwbndHVzFBME50UkVpK2VCVHJDSVEKLS0tIDkvaE04U3ZWOXBFU1dybUdMOWJo
        UHZXY1NVeU5Tckx0QmxTc3Y0NVd5Rk0KZBm1RfyLaRJubNUL8Izsw+yQzXb5Bl9W
        tVfytB0NKmzCEEI65f4O2bjV1kDXHUuiL4gYUL/6//YOCGYXADxecg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T09:26:36Z"
  mac: ENC[AES256_GCM,data:0Cn8Fvnbd5B0PSrFSLxvIDXJL5PK5AOOjA7nxwZkVs68iqA8ZwuMjkmb1UVKuiLkAYlzMENtFWvkZd6HyHaYsoMzGm1CKCYQvvrIOyxivpphhbYxWNURD1V1ThIedicQOYNhpW91RosrfvwSznH2HkiEeDuC5J474Wf2OqlSRdI=,iv:MV61xmK33hkRHKJxEYCM1A5aqn25G5nc7EQHUcXlOFY=,tag:leoXiN/bmo5AEPXUJCCiRg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
