apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:VwKsy/Y=,iv:fRnr27uz3oipLLzBbU2jUZWWo5ECzB5q7Gugp7iGeyc=,tag:idqLjaDRWrWfhbv4xLfr0g==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2Fs0uX710P3B,iv:AZ7elX5a/JXm3iM4gvQn1eN2kEDCV3xSj/Te+Kntq6w=,tag:pW8T6kBRCZlqG/z4sb9JoQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK3c5WjV1eXNoUEVWdE0y
        aFZvVXZ3cUM3TDJKOWMyVmZpemNVaEIvdzJvCjlKSndJYSs0MDhGblhYZjhBQ2Vx
        QitsYUxDWmtLUVlHMFUwNVRXUldlNFkKLS0tIGhBQUY3L0FLTTdHMEdVajgyYktw
        Q0VKTEVhSCtMaUJSZ1RleDU2aXlGTEEKrJLIp3lTgBnwwnqLpqBlnvn8glyc0qbq
        68oicluvZ4Z1AdjZxm6smq5pRcAJDqd0FZNP8H+pCrOTeENLRxNvzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T12:58:21Z"
  mac: ENC[AES256_GCM,data:yyH5vT++yuUYDlolaJ+G8lvAr8igGhX64dlwTdqDH6i+xsQxDh13s7msvmbqnk/W+Oa5QjHNdwbKqMW2SjlxNZetaYewK8Tb4m2051iItuG/2uZxiVb5bCrI36Q5uzXtE5gnVzN7Yn9s86jwiWIcSr4pZ9riJLxYi+E7uXKDaIQ=,iv:o+8hwX4GzA1xEKeHyBdtIRnFfcARxgsf3Agi9YbCroA=,tag:5euGSW9+CdNVosadoVPJxA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
