apiVersion: 1
kind: Secret
metadata:
  name: peanut-secret
stringData:
  password: ENC[AES256_GCM,data:nX5a95EJWR/g,iv:d9bNg67QQPM5uqfAAxPw/lkMCYYB+0BFrlLa2W5MGHM=,tag:NX6azCZjSZF/Mo8R2okjSQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZTlLLzdZd2NDQVRXd2VB
        UktqVkNmWFBNc05LenBQWUpDblVGRzVtNERVCno2V2JydnBudnQwL1NXMnBQTjF5
        bUtXVGEzL2F2TmVSNUl6ajc5T0RjaEEKLS0tIGNQdFRMZnl1c1RnNHJvd09UUVF5
        MTZOTDVsaytUNW95bUlpcDNUdnVRQ2MK9B1n4uICtfDe9R4bNK61kUD20bH9a+Lq
        etOn9gZGs7qo8LvEveS+8isxBmLtO+dGISXW94Penv+JzLsHxYVkTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-17T12:20:11Z"
  mac: ENC[AES256_GCM,data:pyE71dzfoE0WBnq5OzjYbqM8FHSwhS5IhxNBXt/Sa3wp2a+N+hLGf+RJG+5aQXNvnPN9CMW8D0oJQf6+rUyvA5ndVUxlYqb1psDQnd9UJBKo1DcxsVC0rsL3QYRUvabU2EbFNiF+ml1aupQD66/M04BmoKtUt/W+GlvhqYpriew=,iv:ZK4SM2KdzVfxli9YvFreXxZAP0YdWq/hOhl4O/QdhtE=,tag:2R9m6KYfPSBfNSF0SkAiSQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
