apiVersion: v1
kind: Secret
metadata:
    name: peanut-secret
    namespace: observability
stringData:
    password: ENC[AES256_GCM,data:nX5a95EJWR/g,iv:d9bNg67QQPM5uqfAAxPw/lkMCYYB+0BFrlLa2W5MGHM=,tag:NX6azCZjSZF/Mo8R2okjSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZTlLLzdZd2NDQVRXd2VB
            UktqVkNmWFBNc05LenBQWUpDblVGRzVtNERVCno2V2JydnBudnQwL1NXMnBQTjF5
            bUtXVGEzL2F2TmVSNUl6ajc5T0RjaEEKLS0tIGNQdFRMZnl1c1RnNHJvd09UUVF5
            MTZOTDVsaytUNW95bUlpcDNUdnVRQ2MK9B1n4uICtfDe9R4bNK61kUD20bH9a+Lq
            etOn9gZGs7qo8LvEveS+8isxBmLtO+dGISXW94Penv+JzLsHxYVkTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T12:25:29Z"
    mac: ENC[AES256_GCM,data:enfjPU5Zgwv4sDyK/asUTvimJteo9n22x1EQdv8qignwcP6SppyIhF+vYxOJy+NU0XSSReQ+v/0QnNJxqmCxbHvoKBeVaEGiDlpR7hcxrG2Cp++wl70CuIIQz6+u0JTU9SvdWqtRm9YMgyioTB4W1VSuTXbOwci8RxS8fxRBaWk=,iv:b+uhUBjUOYUsy02aC3C/PMwrkQTa+dZ4kZZ7o0/dfO4=,tag:uDEnV9vtFVVOpw/EpOtpFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
