apiVersion: 1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:pwTCb/0TibVJDsidd32CcdxLMQyprVEHPERIEbieH7XQMnacSOPqZEEl00x4xOMFi5LIut34pI8SYYi+pDSbo0vmkj/Q9FR7iCk=,iv:af024wgqJLDN8BNVnExnfX13ng47gSwbmwWpCAAiY9w=,tag:MiS9JGnZUfe/hSRLt3XCpg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1earun57070y7d55fv7ev4sc88uk65tuxyng8tyan77hsp8n57v0sq3jxkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRXEvdDJHVmtKTldQSTAw
        SEE4T21KVTFxbml3SG5EQjFKTXovNnEwRGhNCkViRzNNQXJCSmtQbzh2ZWlKeTkz
        d3BabmQ2ZkdxdmZwcDh3ZXlOTEs2RU0KLS0tIGRhL09WdW5tYkNianoycFl0dXhY
        TjZ0dFQwMzlHdkVoejNTR2NmVWVSa3MKr/YJ9UNUGBhk6IYrHoCS+X6WKK6rbo15
        eoFUjNrKhy8fxoZweiVRbQeQxU1xH+g5tbABqWr3H6L+WX35ow5hOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-12T19:36:23Z"
  mac: ENC[AES256_GCM,data:Um/iP7H7l6dXg8hDnSr4vzy9vEqxSlNsTRB5r0dEQFqsKoLqPh7A9Lvtw6aMYpyusOzqMBKRN28bZzTy1ZKv01o2higHk1fslWfIyq8tQ+bUDo8Blfsp52nuix4n/lCrDnciYE653LcW4os4wR18FXIayVi3tyQReZzrdXKbDhg=,iv:bQibzNCU9lL0kZSRrIv3OhaEXmTKbmG5wahnZI5vOdc=,tag:0NXNuqnqO3Vrs8gLB/QV2A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
