apiVersion: 1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:2pjnSD5Wuq3lg9DCZy4ANlQmGNTJhn1k5C9A7kES3CCTebb/GwEA1jN41vdsqaF/E/dl9JSvBsjdImfdR9+DQjNB+ojZs/xtXoc=,iv:PZYDKZYclydJFZeKTSCWop13ksihXyqUU61UaI14Ra0=,tag:Y/0DPWOCge0yjr7beNIu9Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySHR6Zjk1U2szUFBaajdq
        R2RtdHNMMWJzTnRsWklSejZXN25ocHRETm00CnhVZFlWbW1LQ29CWUs3SXhIMU8w
        b0Z4bnhVQWd1dUVyaTEzcDdBdE45Yk0KLS0tIHRReUNsMDBONDF3WDVMNUJjVDZu
        WXlnMjljTWVSR2JPTTVKVDZsZDVMdHMKnaBdTlqTAuNgquIzMmWSKcu3p1Yj5tKL
        KweWRgdqEtuyhCIm0/Bef66LE0ponz/Qs8e1jYtfZn1aGS+LfJnV0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T12:59:06Z"
  mac: ENC[AES256_GCM,data:PymiT9f5qL/iNDyRSFlKFG8rv4ZeTP/GQLIS5vtuScsAasLiWIHTs70s2pRiTQDGlrC5dIIDEb/0njhWQplwxREHGsbOWiU9XMtqzVEoPO00j0M/vztnNYojOz7kwnyRAknRPzPjklXND7zUS5sucsTLVSb1/a7tN2H64Wm/82o=,iv:Irp6PrVchAUz8C9RsvJcHwaWWjiU7sbsf2nSoxphPtU=,tag:2+4UatNoVygEJOntkpouJA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
