# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XOTGJSlrQXxhBR5Hts7Yld+KaPQV8rV49qF5cyY99Es=,iv:HoBxXCB0icQoiiiES2DP2csNHNYZcqL6ZLNzgLfz8gk=,tag:JhfW3v82a+ynDXF32vWMZQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldDBBVnNjLy8waDhudFU5
        NlB3TVhwUDJBdWJlSUsvdGFVakdRQnlZT3k4ClRwaEJ3NC9abVNSekxYZkJ2MlVk
        NlFuRUpUREVJSkd1R1pYRUhRNDhmZVEKLS0tIFFMTE5EeEJVRjlZOEZGaDJlUTJr
        T0cwWkgzeWR4NnV2SGZscjB6OUMvN00KaYUgakBdKVYjbvtZyT7Tx7sMD6wEiuQk
        YnePc1O3068JPcGOqA6J9BfmFmaUMe477xWKtT31dNKbp4ANc5j1Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T09:45:41Z"
  mac: ENC[AES256_GCM,data:wy+ffYGDnwhMqOp5D4qOyl0tV+QAIkMxga0mi0TbeL+H3G9s/YNy6PPN7CdBaxNoC8IQNXLNTWxbCfV/UX/owBvhNrjro4DXZnhqhITO6WF6sYx0k9EY3cEjX210apyg/TC2W0qnyI6PgCBRxX0XAK/enHIKo4Z+t+3FTFGp5jM=,iv:P0zrhO8MmGK2IgZQlfWKIcvPw0r832bJE7+60CnlAyg=,tag:ZDGJuSByS3RZ3X2GlrulBA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
