# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ug63onf9Nft49xaj1tn12itnIzwHy/0BGCMfTidj0Gw=,iv:+frGTSFRXyRg5smdeExl4q278+753gfyzWcyaa9p2Lw=,tag:XeJ4H769Yoc3b/C8GWmd6A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1earun57070y7d55fv7ev4sc88uk65tuxyng8tyan77hsp8n57v0sq3jxkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRjNtc2VMYkJ4MURHcmtl
        UkhGSXg2SzZEWEJ6SHhZeGhuS1BTaWY0TjBNCkhuZjZlSUtobG1oQnI0MU9kT1Nl
        SmcyQzZ2aTFIK21PblBGRXBMQ1FxMFUKLS0tIFVaVGNGK3VpN1JmbC9XRmFhMkor
        Z1FuTnJMNklpSm4rMFAwLzRmVWNwejQKFrYrvdH4lUgNVDlxHc2pbzxvBP9ioI54
        Yyx6wV8iAauzmgv2mi0rzjeCwydM7J8YFLnHYow3YdopVAQ2e6aUhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T10:59:47Z"
  mac: ENC[AES256_GCM,data:E25p38Ke9x9B8sL13ZTxKB7rDVVSP5J2vrA5LRxDnv8wkBj2fsLXddNPwBxu69dJsi4HRvU0A64jXFYPj4i/5yVFWJnDxSKvKas110q9KlPM3Urgk4ZKMup/lS5uSxErNkNCkwfN5Ab/XoGLzV581XhTlF87ObUkiE0dFMTEi1M=,iv:yhzmAsStY8yLBHTkqznbhdtvq+cMNt5LorpWI60+z1c=,tag:45VA+buaQPQCwfUHi7WUXw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
