# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:yAhoR4brloi3oilaqAjJfSeIg7ADCz1SVO/dW4WsFDI=,iv:MGgXRxe7zpseLwiHMz7aFK9h4cT1PVVyfU5mzFG47qI=,tag:+JolUwGdRkYYruMPFxHQiw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUm1FOHdYbzdVaUxOb3Z3
        cmRUU3k0dWU3MVNQNldmWnJ6alp2YWQxUlNvCko5Z3k4aWZtdXh1bE94OGVCNDd4
        VEc3REtTRUgvckkvME02VWhuVnR5MjAKLS0tIFZGVTNVSkZuNTd1U1ZwQWZRY1dm
        eVRNQnJqMGoyNjJhWE1CNVZKYis2N0EKME2oIvVRiaLsAkisyfWgIDE9hCdCRZnr
        NO2PGvCEprIyjd/UEHN/70SmwwrG6uMGuD16Kdzx7KbarvnwjuISmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T14:20:13Z"
  mac: ENC[AES256_GCM,data:tAPSX5Q86dkJ1SO9OM0aYKNefftWse03QKeKZBD+i0t+sMsvumIsAdbFPZMlsSD2mKpsA/tVq0DJOsoOcF1fuydMs1MMjZH80Ro/Ur6EsqCo+X8MbvrsRByaTwiWiWABX8U/u8l9JeRe9XCciLPKgexcPTKcZjiy6wNgGMgAhX0=,iv:BFLR/Uq4E59rDbQyier8BLVk7ljBpsiv2zwe8dUuZls=,tag:IP7KHCIQBRmdM4h2VQ2uNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
