---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  target:
    name: grafana-admin-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-user: |-
          {{ .username }}
        admin-password: |-
          {{ .password }}
    data:
      - secretKey: username
        sourceRef:
          storeRef:
            name: bitwarden-login
            kind: ClusterSecretStore
        remoteRef:
          key: fc2b001d-f66f-4235-b91c-cf5a6b7834af
          property: username
      - secretKey: password
        sourceRef:
          storeRef:
            name: bitwarden-login
            kind: ClusterSecretStore
        remoteRef:
          key: fc2b001d-f66f-4235-b91c-cf5a6b7834af
          property: password
