# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: flux-github-token
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:oCvTf1RMG9AAk26T9TNqmxlANQcqd+JzupJ3qHA0nKZ/f8tViyHhdg==,iv:z2n+Ho3lOzfZdGfe1hEiKGUkWMPt17Bw6y6iXDkY9jc=,tag:Ih3iyzoOi0lMOO89xiFqbA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MlZYWk91M3loQXpEL1pD
        WXRYWHg0MHYvMy91RVNvNWl6VXBVbUc0bnljCjNxeTkzVURTVUJtakZoMHM4RVdx
        QUtqK01HN21abVJseENoa2FSR2VhQk0KLS0tIC9Pb0dwS1p4L2hFWEpIYTlqR1Z2
        Q1c3aWhiVVZUN1E4R084SEZSUGYyaEEKLkXUAlSCYUMGLmXfBT5cVgiWxjikGLRP
        nYHGkGAqPQAfFIpvFn8rur9DmQ652JGzgXkoGU6QI1GNp0epOQXLmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T13:00:40Z"
  mac: ENC[AES256_GCM,data:ZaS+XsckPJ+N2HQlx8Qg/SHiZn4tFFLLqRRPLEpfUCTqTrjhXwNgIeYOKLXvKEdSVE+/KETDfcQH/mTx+rwJGsK7ZljX5hMmCVc9222EtOGAoZcMB3GdBrYUPYLSLvTx8iCg2MT679uz6Hk7xFXAvMxVS9iEqp3ZhzVkz3q+xhw=,iv:xz6L+HJEQnoBKGe+Wc8heImM/pdGf68kfjLMex2yQgo=,tag:jgLgMifbkzv46188Z8o/cw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
