apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:STpSXVqadaa4ClQ=,iv:Xt6Wk+3WHXVKWlTB8ovUUqLiRRtAkmOmEl8dQZF/QEY=,tag:3DK8MIAcmPOfwADWW4bVbg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1earun57070y7d55fv7ev4sc88uk65tuxyng8tyan77hsp8n57v0sq3jxkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSFlmRWQ1OGNSeVBIY281
        OTNDMEVaSk8wNVA3bXg1blgvblJKaWo0Y1ZVCk82U0VLQ1JwSEVlN0dBeHZ4aTZh
        Ymg5RVFsT1ZzSUJWem9qaDlRRnozQVEKLS0tIHRjOGNtbklCdmlGaWFtVU43VlQz
        RS81R29lZktxRzh2cHVSdzdvNVVvY1EKvY/N5DnsOeC2IwNRJ5S0IQ/7sZRIz5Jx
        EH4kliq5kfeGrYXgmLCPo2D2cwGP4OdxRBsrCFlBSuxWj1hrYWKB/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T10:59:47Z"
  mac: ENC[AES256_GCM,data:FQyUkAJvuYpJjhTJKLQOzcEt4eVKvzUoit9snv6yZG0Hu4iZQ5wXzouTj81zgbMHzmRmQ+jPHzdmw1iFqCQqzaOu3WYM99NNCyen+OUg25Y6mWIg7NOnG0HsVb0q7qOzH6kvmXmBYt8h5TtiF8IXSMSJu2OvrpRd/d3R48gEjkY=,iv:Ij7lWGxeK9KqY7Rerp4ja5nhFEVbVWPFrWhEyHHSbig=,tag:sqvoXiUoisT6igixXMS0Ag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
