apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:FqUCsKVg0N+NFbc=,iv:6h/shOnRm+xvqeQLs1vx8IRB/T8HLs/hEqWid70C0CM=,tag:peuc79FoNN7IW2AOvlh4mg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MTZMaHMwYktKdGR2cEsy
        Um1iWm9jcFYzcXExOG1IRUZlRkJRdk94Vm1zCnVXYXcwbkgreGtjMWY1dlZXZmFF
        b2hOMDRXZ0NvMWJIbGQ0di9SL0VoSzAKLS0tIDZjTlN0aThuNi9ZaGhLZlo0V016
        Rlg0NVB3OWtRT2dDOEd6TE5hdjRLc00KbFDLWIDPcpviBNo6ljJbXJZf46sZ+j8V
        AS99pWBEGd/ZwCwX1UnGDQAjh06u3pYHrLeGTEADTMlzTDIuP1iA8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-27T20:18:32Z"
  mac: ENC[AES256_GCM,data:z1qniUbK7CWRlmOffUllKotbnVn898kF1HrLzxn+ad3L/oZFZSVH087VceCKpwWoSBn+GGelQkYOPXR7wRz1ogmxLUDds9fomsadeKJ42yZ5HjrTmUD+NoCOPxNeQB9/9bZ7Wro3pSSMyvpOqdo2pYme0kqbFrxJbMyPjN5gBj0=,iv:h1kBFohj5ScBRMZ0dDd6CTWPDmaKbGtPhEiILBrLgEE=,tag:P0DAhBavy2+F3IVxKm/2Lg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
