apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:uL1RF7iX6l/B1ec=,iv:VZyNL8kPrDAOof7kei7u3OUb+tMBgaIQSU3w6n7DQJ4=,tag:Die7WMCGlBTUHc8PT58hFg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBickQ3WER6TitKcU5yR3Iv
        Mk5rWnhYNUY2NnB4U1Fia1U5ZEtxZVRPZVhzCi9lMWpsdjVQNDVkanpCTitKSFVB
        RG5OY3NKcGlRR0xtTWl5NFpLSGREdXMKLS0tIDRtVU5zS2JrN2JqTFE0U1dwWWVl
        OXRNT3lJMmJLTjBiRHJyUlNxZkVaMlUKH8KyJvdRWFUoT8VM6dO5kmHssrzx7Gmq
        BdLzUfM26EehBYTjPPgwzVjAOfKc1UpO47OzjB5qotFDWXZ1wCZRaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T14:20:13Z"
  mac: ENC[AES256_GCM,data:1zAp5nX6wNpF4ohBj9xrPq209CCybW5AOR6AS+9cubA7X8A2EMqSurmLAuLHAfrcq6clHtOClPKCNaegm1VDEccqcx5gCVGF4j2XGHoKW/JwKTmtxBmul/qm0Zriag6XDLrIaAyz9kD8iyRb9sEx9Sg9sV868Pni0//fgwlatQk=,iv:7CA0KSPeiB2abqbBJhEUhkF95jPippZxsSKXS7aDsP8=,tag:F911uRd9gVpDMvmDLyasQQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
