apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data://asvW3c4Ct9gIxTONu0246v0c2gTgy2PoiiAQ3Q1fg/DjQrTtYpXaBL9qDVVezkh2IhhUt0Anqrms7UxIUN6e3QBKfs4VDKcHk=,iv:mFo1tFUsMNOy4Jb24NLi/3PIOfmzVGFXz+EaR+uYHmo=,tag:HzwBaCHqZW3bWumqruyvWw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza0MvY0trL1JTS1ZIUExx
        alVaNnY0VTZ5NTdMa1lxNXMyeFYvQnhOQ1VjCjU1aHVDZUI0Si94cloyY2gzYVUw
        VmJEOVkvdXE5Y05taEVNZXUyN0lCb00KLS0tIFRsTTUzakdmY25lS1AzN25RNjBt
        M2pMV1JHR0srN29lY2lvWVFuYThOdU0K1oDGKIze8yK46ro+54dad0ZOnSusoCiM
        TDduzinY5Bm6iJT++9c6ZwLP58TqTs3CVzVWHj0w3C4L4YAoAVFT9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T14:20:13Z"
  mac: ENC[AES256_GCM,data:klFzp1xs54cL8NilWsR+OdrB2gNcHN3VXrcWmqvbOGYCcT+arPlSW4Gw0kCFPmFq79gq7j5O480JjfP27q2XjArWVnotkzYqRWY2JUg7rgApSVtASuxSjLynnlfma97R0/75/XPXtM86ycDQRiVEUZRg3AwjutxNQrlo77BsiBo=,iv:T9HtpUMhxeGpamgWMatlvv2daxS/9ADaJIoGjOwALD0=,tag:M5ETfynMspt+VjEF+/IDbg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
