apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:RBVHhrnz8vBv5SJ24SmOoHpnDXhX9YGvi8CeSL0Zv7YlrEOAwbjKtyWO+AU+b93peZWurMRUzcxJP3CvO2i7z3JrR6/ClAXik5c=,iv:ErbJ0aA7eNQu4KgCyuETL+LEN4Y68xpVKXGkpPProZA=,tag:53McaMi7XMa8fB4hQLqyKw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZThya2lOcWRFN3Q5Y1JG
        ejBPTWNYL28rZnhCb2dDemJhczhyaHRjdFF3Cjc2R2V3M0xvVkVQN2dyUEdIOTdz
        VW96RDRoN1ErWTE4b3o2M3FRdTJBK28KLS0tIFZuWFZyRU15d3VqM1RCV1JDbFVD
        S2EzTmV3aUVuRkRsUFVSNTIyWEtjNXMKS8hGc8ObLOs3cmlnew2a4XZfRN/vfpnt
        tb/QUw6ESidd2yB+oLkXvXrk3snGszSOct1OfglUZkiqgQSmXHRM2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T12:55:21Z"
  mac: ENC[AES256_GCM,data:OYH8yvxR/RY0zB07Hhuxj+XkhsoFjyHYV7zYATQ6qNR0MkUJ9otW8DmD5R4cA4yCNOsz8bLU9lp4T4QLLzemMn1NdNqm4i7Hu578EI7aCXnO6pJukKdNg3mcLJqCRRwLV7ErY5vGYdUJeODGdpVjMg//XHSt5S5JKsUGFjpJ7MI=,iv:xDgexSfi4xIPPcsNY3NC2EHQHFdT5ClmYjMYjmRRGsQ=,tag:KkfXDLL9Sw0kUMYGUPWQVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
