# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NIw5yVBa0VeG4S6sTM8X5gCSzq7rJMJV7N4IIom14wQ6A6AqojBf7w==,iv:GaUs9ZINLEb28iiFg7mxJR6mxWuQtQah7DcM03L951A=,tag:XYIIef4Eygn8bQaHkgjHdA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwL0xVcklYbGdIZDlYN2Qy
        Z0lvZFRyNjNna0RzU0lBc3QwVWIzWHFEU0hjCkR2aHBZMkdLYnZEZGtiaHJNTE1u
        cHQrSnMyQW5LdklpYUo0MVhXaXZ2MDgKLS0tIHNkYjFtVU50VGF3VWdjT0kxb2Va
        cmVCd0hvcEJUb3NaNThuYVIwRUhtN1kK7D+awCJgGwBUpTfDix2OtabtrgStT1xo
        Xrpaswd+tJlnIZ+EHIRGnIg7pbAMPi80ov5ln2+1MP02tzLE0VcZRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T12:55:21Z"
  mac: ENC[AES256_GCM,data:TZ2UVOzcvheqHvX+8ikFGdLOG/ATjZHKx2088HCtQo3kZCD4rDIby8ObTL56PBHQCr3Hy8HHXjokDSonBIlb+LmSBIRzIzOYVgTZ9D/xspELIewKlLQTOyDJxT/TrVfqB9B/GyIJWMEsKTK/YbSfSvIqirIL9xyFYmQRDBtYbVg=,iv:hlRs06q/WasAtQ5GOUkgpfQts4ie1xkPPUvaFhMMyPU=,tag:3rS6qc2fRVPPl0Fd7QTpug==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
