# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DzssgDy1WumKtIFWNHs5s7lBW+6+G5SW63HEnBZwDPK0yiueCMYXaQ==,iv:ZaN/+fxEuMyxs9KgvHkTo5rXiVsnnEJryF+a10P44Ek=,tag:ZlrEI4KR89/vR0BDOnvrZA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWlRKQ2c3S3htZjJ3NlF0
        UXM5NFBPV1NTbXlUMU5OZS9XZ3R6aEltQ2lnClJMN0c3NlNFQ1dCM1VPT1diQ0I5
        eVovZ0JsV25TSUVhbUc4VDRyYlBlSUUKLS0tIFZ5SThScHBLMHg5emlsMS9QanJN
        SGU1aHZiQlFzeC93cllwWk4rUmxENFkKUuPB4PX+8Qwer5Xc1+7fvdt546HnKsWG
        afJ5+2YChLqzM3v/HbL5Em+twXwtYdVVZxoaz9KZbnb2P8EpaFeOMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T09:45:41Z"
  mac: ENC[AES256_GCM,data:XgILKzCK1wSyyuN9DF5sYnq/I7qjlRohj1RPZj14ID49G3zDI7oEOxuSbK1AXayuOLKDy1Oodla/XpMSacdN/eH7FqMa1o0dTyMravZPAIBVkMQzEGLdHCz+hdUUB+wvZJv0J5K5zwa0F0KetlsapIumXJSC9MAEMD9NTWUef6w=,iv:khaD4fWV9feBM18pXQSnS8WKm+8SdL1w5pa39WPaKHo=,tag:ugp7YUNOh7o+K7ObJl6xPg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
