# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:9VEvzj5iLpMTj5TVeOxG9FTiZUHnAzijrjRUAJYDF8VuGB12ZIa6tA==,iv:TSt9qbs4iE4Rt23B4jeYHsQj6H8RWf0Expdj+QB4wQk=,tag:oNOuLFVSPxu1JRH4keGr2Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1earun57070y7d55fv7ev4sc88uk65tuxyng8tyan77hsp8n57v0sq3jxkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dzdmQk1WV05RbDByYVFx
        V1h1REMrb3RHVGJmdFJ3RWNtcEpKMnAxYUNvCm5wazljTGsweVZZenhrZU9EMzVk
        TUIvZmUrNE5lVDR1N0swblo0SDZBcDgKLS0tIGxOdjFmMDZDb1Vwc1BnMUkrcmxC
        Z1R2WVE2a1dOQUdGRC9PRWt6UDBjT2sKGWDmBAHBhgFw4PdDEwikAy23IyUGv5fY
        jGcUP6z+FdhXcVosZ71rHGBeqKWSyi9/S4fNPRWIdWSAFULXyY5gmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T10:59:47Z"
  mac: ENC[AES256_GCM,data:yzyt90mfiIb07wFGa6Mx9HNVaa/rsFdJTPM6+vVTdMd/kOlyotccGiIlyExmLTSh7vf+XU5PXtjBmUVkZJuityLmYyLv0b5aNinC4cX+dztfBX1X1v4QLBLArXdauTE0em3RQ2Gr9u12y9YwmrvBpKzMfAjGbwGcPoUaem7Jocc=,iv:PC6p38h5zr5V4Szbd46xZq3p+4tIF9nEp/96aTX+ktQ=,tag:AaFild3IL99UVG0ncgfnNw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
