# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.7.2:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.7.2"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos1"
    ipAddress: "192.168.7.118"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/2d61dd07b20062062ea671b4d01873506103b67c0f7a4c3fb6cf4ee85585dcb8
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:16:3e:ba:1d:ee"
        dhcp: false
        addresses:
          - "192.168.7.118/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.7.1"
        mtu: 1500
        vip:
          ip: "192.168.7.2"
  - hostname: "talos2"
    ipAddress: "192.168.7.182"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:f1:40:59"
        dhcp: false
        addresses:
          - "192.168.7.182/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.7.1"
        mtu: 1500
        vip:
          ip: "192.168.7.2"
  - hostname: "talos3"
    ipAddress: "192.168.7.192"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:bc:06:59"
        dhcp: false
        addresses:
          - "192.168.7.192/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.7.1"
        mtu: 1500
        vip:
          ip: "192.168.7.2"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

