---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: ExternalSecret
metadata:
  name: unpoller-secret
  namespace: observability
spec:
  target:
    name: unpoller
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        UP_UNIFI_DEFAULT_API_KEY: |-
          {{ .unifi_api_key }}
  data:
    - secretKey: unifi_api_key
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: unifi_api_key
