# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: homepage
stringData:
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:r6fJfdE=,iv:ezOppf+XVqazyGZgGKGNh61If3DB3GmwfeI8aXYpInQ=,tag:C4heh2elpOZPJgJhSj8shg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:D5vuud4EIzjO,iv:TDbsBvnelWIuRv4wDQny4RAKjzA1FCj8HkKuYkBP2Yo=,tag:z9BRv7ZGuOBlAHDXAWceEg==,type:str]
    HOMEPAGE_VAR_OVERSEERR_TOKEN: ENC[AES256_GCM,data:XMfnRDwQA0Qrjqac/xL/rVku4HMiPwGPYw+SZ/Niamc/9AFqcu6TttDDxnIyHf3JPjuyptrMTzCvUm0Uen9RpXqZ7pQ=,iv:9X3xFBT1lVyBF+aN7zodPQSrzqWnExRfUbd9Sjy25Uc=,tag:Hy5Jor6AA6BHQq1KCVkRxw==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:UXGvTGFrz09Ink+A0Zza7GdybIk=,iv:b23uLWKmnqytrz8evVpyAbKIiByrbCzlX04aC5jGmzQ=,tag:FnWyi5tnHQtEuPiIXrJvAQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:qHXZi40S49waEsQ2ifuuxQCuW8yvAwUiImz7q8ZMMSc=,iv:aV38GhsMaTMGjedzEuAykhVSigDHraDsJKAS5wzgV00=,tag:XYXGVsLxiJ3TIZrQVsTitQ==,type:str]
    HOMEPAGE_VAR_RADARR_TOKEN: ENC[AES256_GCM,data:jTRM/YAR1hN/6DopGMs0kLsO951Y8Haq2wkaQvvd/QY=,iv:aLxYc5RDPPpDzJlaXa28U6x34ZVKS772DmW9wvVy4RQ=,tag:cTBryHsppOYEk1ImOCJIbw==,type:str]
    HOMEPAGE_VAR_SABNZBD_TOKEN: ENC[AES256_GCM,data:QI0DEZJ8u5c1wSCjwWYvcteEzNXMpFi59tIDnJD3vvU=,iv:NqTbu67gFBmD0phLPtIb9cRfjCBdgTNFxuQ9+V1Tffo=,tag:Ux/E47tIyKLfpAsnA1X4sA==,type:str]
    HOMEPAGE_VAR_SONARR_TOKEN: ENC[AES256_GCM,data:/h/JzwvFcPVaO8X/LOhHjO7XyCJq+nI0Gv0w0uOt7r0=,iv:/iGqxX63DWqyMDMJf5Ua7FYux0pDxo+gMNfN0KzriRs=,tag:6Q20xf8bjyvlhrXYZoRxfg==,type:str]
    HOMEPAGE_VAR_TAUTULLI_TOKEN: ENC[AES256_GCM,data:i3KVrFdRKTKv4D2sNPHN9q8lB8cOBOhy3bwy5gHChZg=,iv:ITZlPlBUPeoeUcA5pgGWWBCOJEIzgVPUYdD8HP2aJTQ=,tag:i0OQpbbYa8ahpG8/xcUFHg==,type:str]
    PROXMOX_API_TOKEN_ID: ENC[AES256_GCM,data:ID+6WgNYjh5uROPMqgNKtog=,iv:We1kqvcEfbF48NueDSvEz9VslYduRRcPc4fsqDicKAc=,tag:ckRwSyBurJtj0rnGQXUYig==,type:str]
    PROXMOX_API_TOKEN_SECRET: ENC[AES256_GCM,data:NY0rcutOsmXOGM/14ZyUEzrfNS7uz2ujcCYUCF+QamS6WXkX,iv:8/KV2aOv9QqKcR6u6F/Nh6+Rc7IsU+yn9UuP+W4XTYA=,tag:jfzQI8k36KHNJV2F8RQ1JQ==,type:str]
    CF_ACCOUNT_ID: ENC[AES256_GCM,data:r6fQ8OZdYtRpM7r5bmqJFsGMLMA9YePd0RFQWKuCYcU=,iv:KZlLj8jQWkF44a7XUKp21ZFZ5l8APb6XufY47vEKU2w=,tag:n07+hKOp6NUmTZxAT3zlXw==,type:str]
    CF_TUNNEL_ID: ENC[AES256_GCM,data:J7DQ7lC9BT+7m0ECp84zD1ipvKrlOaill3aeWnTGf4I2USga,iv:gIEC+wusgHNSjagUKPQapOj9KvN6rUkbvaVrJ2AN+Cg=,tag:q6KzMBBmRSTX4L7/f5cZTA==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:qrG0u+KS9/iKr1ESTzXLp5ptSwqeAM3pkYm1/nLMpKR8ze9y7lOwGQ==,iv:YZWuTsrjdGbuhZghLcF58QNi0+jOCtXkpD5R58ovsiI=,tag:rXiiRzrJXnWBELbX53qGng==,type:str]
    HOMEPAGE_ALLOWED_HOSTS: ENC[AES256_GCM,data:f5khEBRI1CVdtUrGB0Va7w==,iv:Yz0SapzRKDhoFGeZVOfBF3HxSBGax1AYY7jZP+8Y6nc=,tag:ulJ2pzBPy5pMmB7nzg9nkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNkJpamdzQVoxM1dENDha
            TVRMUUJMbG1mdEJyT3owMGE0YlZKb1BNNTN3Ckc4czhWeUVocTZJUDZSTHlqdGg1
            VzNXOWU4bjd5ZzhhbFc3MzhpdU5oRjgKLS0tIEFXTlZ6R1BjWmx4VFFIdGFxTkNQ
            c04wWFJITkdIK2NsMzR5aWdJTnlrMk0KlUFua7UtYcDeB9GuiOnPze2B3ESP3p9f
            7yWA+Qj+rfIeXmAzQaPtql46YY9NwnMpyT2hQosi89/5Aps2pV6u9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T21:39:53Z"
    mac: ENC[AES256_GCM,data:3U5GzQYhT3MApkbqhMCuDVnVlgq23HxjyIo7iSOIs+W7GYPhMUWxKWT9C7j3XbmyPXmkfcK+g2UqKyHMZGU8wagaPKJnVkBIg/pWn8ICUPd/O0/Hh77RiRIjyeW1QKnyQWoDZ1roL1CkKlJAcIVEBUQhPGs3SUorq0JELAlP5Gc=,iv:QLlyQ3AuY/fHrAORczkyj0SFMKIEIA42QDy4DBd64+k=,tag:4Lv21jAkhbH6aDTerzK6TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
