# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: homepage
stringData:
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:r6fJfdE=,iv:ezOppf+XVqazyGZgGKGNh61If3DB3GmwfeI8aXYpInQ=,tag:C4heh2elpOZPJgJhSj8shg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:D5vuud4EIzjO,iv:TDbsBvnelWIuRv4wDQny4RAKjzA1FCj8HkKuYkBP2Yo=,tag:z9BRv7ZGuOBlAHDXAWceEg==,type:str]
    HOMEPAGE_VAR_OVERSEERR_TOKEN: ENC[AES256_GCM,data:XMfnRDwQA0Qrjqac/xL/rVku4HMiPwGPYw+SZ/Niamc/9AFqcu6TttDDxnIyHf3JPjuyptrMTzCvUm0Uen9RpXqZ7pQ=,iv:9X3xFBT1lVyBF+aN7zodPQSrzqWnExRfUbd9Sjy25Uc=,tag:Hy5Jor6AA6BHQq1KCVkRxw==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:UXGvTGFrz09Ink+A0Zza7GdybIk=,iv:b23uLWKmnqytrz8evVpyAbKIiByrbCzlX04aC5jGmzQ=,tag:FnWyi5tnHQtEuPiIXrJvAQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:qHXZi40S49waEsQ2ifuuxQCuW8yvAwUiImz7q8ZMMSc=,iv:aV38GhsMaTMGjedzEuAykhVSigDHraDsJKAS5wzgV00=,tag:XYXGVsLxiJ3TIZrQVsTitQ==,type:str]
    HOMEPAGE_VAR_RADARR_TOKEN: ENC[AES256_GCM,data:jTRM/YAR1hN/6DopGMs0kLsO951Y8Haq2wkaQvvd/QY=,iv:aLxYc5RDPPpDzJlaXa28U6x34ZVKS772DmW9wvVy4RQ=,tag:cTBryHsppOYEk1ImOCJIbw==,type:str]
    HOMEPAGE_VAR_SABNZBD_TOKEN: ENC[AES256_GCM,data:QI0DEZJ8u5c1wSCjwWYvcteEzNXMpFi59tIDnJD3vvU=,iv:NqTbu67gFBmD0phLPtIb9cRfjCBdgTNFxuQ9+V1Tffo=,tag:Ux/E47tIyKLfpAsnA1X4sA==,type:str]
    HOMEPAGE_VAR_SONARR_TOKEN: ENC[AES256_GCM,data:/h/JzwvFcPVaO8X/LOhHjO7XyCJq+nI0Gv0w0uOt7r0=,iv:/iGqxX63DWqyMDMJf5Ua7FYux0pDxo+gMNfN0KzriRs=,tag:6Q20xf8bjyvlhrXYZoRxfg==,type:str]
    HOMEPAGE_VAR_TAUTULLI_TOKEN: ENC[AES256_GCM,data:i3KVrFdRKTKv4D2sNPHN9q8lB8cOBOhy3bwy5gHChZg=,iv:ITZlPlBUPeoeUcA5pgGWWBCOJEIzgVPUYdD8HP2aJTQ=,tag:i0OQpbbYa8ahpG8/xcUFHg==,type:str]
    HOMEPAGE_VAR_PROXMOX_API_TOKEN_ID: ENC[AES256_GCM,data:i4POxd4q5c10WvL/KTch5Ig=,iv:etkMIFFZfmVExyttJ9CVR7g/mVnr/K16P8LpOJaRR98=,tag:Je7xaopcEBv+wPqhQ9CaYg==,type:str]
    HOMEPAGE_VAR_PROXMOX_API_TOKEN_SECRET: ENC[AES256_GCM,data:Qb3o+PewCYQLrIo4JD8IMju023NGPvk98Kj7ziLa2bidoyou,iv:izuY+P19tYy/q7ZJI3UMpbUja0qLtkjG+3nQimRexGE=,tag:5+CCaSwle3Gq0daw8Ak5FQ==,type:str]
    HOMEPAGE_VAR_CF_ACCOUNT_ID: ENC[AES256_GCM,data:r6BW4RFo1AHDQ2z6nEIaeSFPIs+gMiNdTbAZJKl8+lU=,iv:m10rcWavkflSTtzb86lEaja3MuuysCmaaHQa0ubrq2o=,tag:Q5vZMYvlqg4Clm6WOUiiqQ==,type:str]
    HOMEPAGE_VAR_CF_TUNNEL_ID: ENC[AES256_GCM,data:Ox+pvnjeKAwrm3+Kp8eyX9HnE/ic2P1gD/EO6v+28zfV1D4d,iv:SxdHZJd9pUYXbtQTxemmxHT9ymC09op8MXeKlh6KWK0=,tag:EAFohv+pOxN5Q8yKV0kF/A==,type:str]
    HOMEPAGE_VAR_CF_API_TOKEN: ENC[AES256_GCM,data:LckTJpHclyvk8lw6zwz5Rfbr8/RITesmgbifgV+ge7LNThuMKU3yuQ==,iv:oNAT8CT9zisVgyUmw9rI1lSNf9WiMVJwVFz6I0JD6J8=,tag:Auec3Dhk80TyZu1UYIUfLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNkJpamdzQVoxM1dENDha
            TVRMUUJMbG1mdEJyT3owMGE0YlZKb1BNNTN3Ckc4czhWeUVocTZJUDZSTHlqdGg1
            VzNXOWU4bjd5ZzhhbFc3MzhpdU5oRjgKLS0tIEFXTlZ6R1BjWmx4VFFIdGFxTkNQ
            c04wWFJITkdIK2NsMzR5aWdJTnlrMk0KlUFua7UtYcDeB9GuiOnPze2B3ESP3p9f
            7yWA+Qj+rfIeXmAzQaPtql46YY9NwnMpyT2hQosi89/5Aps2pV6u9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T19:11:32Z"
    mac: ENC[AES256_GCM,data:ueB0P5g0dHx2rDAO9PpqrPHmfzXQa3xcM4/elvnUQj0IQ2wmlSuYTxzgNK+eHt5jFC2PwqrHaYdwqBfDYuxe5lS7ddEedWMsVdlOiKfHs68OiLElHlQCpXGWGiEbHBYjYyFvCH6YZ/a7T/O3YmW2ni9bCO+G/U2glXu0oanWSMg=,iv:yHWUH5DGueoi1qvE6CrEb3Z57Zac003/y/+1atdgajA=,tag:1LUxFgitOzYoPa5lPMzFZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
