# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
  name: headlamp
stringData:
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:CDyH4KpGM9rwpiOqB+96HzoEUgCLInwgepEpDg==,iv:TgbNBorJ4nb6EEIuZgPlPPs9SmYu00f2V1heaWgrAyc=,tag:q8NwPMbePvq2/JgGtkPzmQ==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:3tdau0Eb8lFZq08nbANEBPCV+My24uF0kyvt/g7nlA6SPdEZ7mCjcQ==,iv:rb1NYrk95FnMoQuXVDG/HQsb6hcXxAbXtq/q+Zx42tk=,tag:xytQnj2K/b5c9Sl+LGglpQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:986DYh219BS9c7cnpahJ9irAkXlaioVQpdcUWp7q9QsHiRAvIEcw44zjYY4WR5+zqHlFsS4HeY55eLbYLMaXDFaOIPl0l+Z4uhDCtPcWfyWh82NJi3UXMrPyEKqZY9AdKrUkegubCfC4Ud/saYy1w8ZD6wxg1ewaX3GUNJGLpJA=,iv:x6JaNPLVGXPIHno7yCo66D+Nkos6CfdtZYVSo2tVOsQ=,tag:D3UlNc39K1Xa5gHZS2o+Aw==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:amrhGILhdOS01L5IsETJzEhVQ7ydrH4D4sn4,iv:tDIRGGD3eurde2WmZ+SwGYpwBBOgSbuXxK3iMfM6mfs=,tag:OgN0K2BByVBnD78QFCDQMQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVGxQRXZucGFCNE85eXJZ
        SDl3NUVaN2JOY2VzN2dDbE5Ha1hVdmZ0ZzNRCnhWTER6QkkxWkswTXV6cmh4VWx5
        RVJvOG5LNHNVcFlMRDdXRnc4SklMT0kKLS0tIHFvdzRQa0VMdnZrSFhOY3N0L0pp
        SFhOdUZaMmpRSE0wd0NoVnR6TmNKdHcK4dXPZuuXzMwBVGAq9UGbn1eESf8BCOix
        YfHBmKBotKxECvTjyoxDsX+5MpJBUopFnaZb5LUaUvYaZY3FV9PqxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-17T20:45:46Z"
  mac: ENC[AES256_GCM,data:xxGPsvnfYYd4RDxFRXIvKgy9FUXnAL0/V7flIKW6QVzIpthmdZ5zOA3JcyN53ZzcNIek2fpbO6QakkGgVHq0KD/e7m7KOyobtiKZOIah8EaxdZrN420CTYG5mrgfffy865FrPIYxs9WDEgYwMD8WcnIxOaF9vEr0M1elcd99Q+Q=,iv:yHb+FeTVO8Q5zG2GUXvmIzC2B6w4co02oaYR/kG5/z8=,tag:YmktNfCc87qs77WiavZB7Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
